### ISSUE TITLE
11ty.js layout with required scripts is not updating

### ISSUE THREAD

**Issue by cawa-93** [11ty/eleventy#1435]
**Describe the bug**
If you make changes in javascript files that are import by the `required` in layout, these changes are not displayed until the build process is restarted.

**To Reproduce**

1. Clone [repo](https://github.com/cawa-93/11ty-issue-demo)
2. Run `npm i && npm start`
3. Open http://localhost:8080 and check text on web page
4. Change `_includes/test.11ty.js`
5. A message appears in the log that 11ty saw changes in the file and restarted build, but on the web page of these changes it is displayed even after the update. The only way to see these changes is to stop the server and restart it

**Expected behavior**
Changes in the files that are attached inside the template should result in a change in the resulting html. How it works if you change the file `_includes/base.11ty.js` directly.

**Environment:**

- OS and Version: WIndows
- Eleventy Version 0.11.0

**Additional context**
In a real project, such a connection is used to combine several small parts into one large template ([Live code](https://github.com/cawa-93/kozack.me/blob/24e5074c6b5bd7d096b4b05ac01bd44328f0afb2/src/includes/head/base.11ty.js#L5-L8))

**Comment by cawa-93** [comment]
Maybe duplicate of this https://github.com/11ty/eleventy/issues/1312

**Comment by vuolen** [comment]
I tried this out but updated to version `2.0.0-canary.24`, and the problem still persists.

**Comment by dospunk** [comment]
I'm also having this issue!

**Comment by zachleat** [comment]
This is almost certainly solved by the new dependency mapper in 3.0 but we can circle back after 3.0 has shipped

**Comment by kkukshtel** [comment]
I'm on 11ty 3.0 right now and am seeing this exact issue still @zachleat . I'm also wondering if it's less 11ty fault and more about browser caching?

**Comment by zachleat** [comment]
Confirmed that the provided test case works in v3.0.0 on Windows. If other folks on this issue are seeing a similar issue persist using v3.0.0, please open a new issue! If the original poster is still seeing this issue persist on v3.0.0—please add a comment here and we’ll reopen!
