### ISSUE TITLE
`ignoreFiles` bugs?

### ISSUE THREAD

**Issue by davidhund** [11ty/eleventy#35]
First off: 👏🏻  for this!

Coming from Jekyll etc. I expected underscored folders to be automagically ignored. Especially 'system' folders such as `_includes` and `_data`. I understand that you want to be more explicit with the `.eleventyignore` but I can't get it to work...

My setup: input: `./src`, output: `./dist` with the following:

```
# .eleventyignore
# NOTE: these comments are for this issue and not in my .eleventyignore file...

# Try folder-name
_includes/
# Try specific file
_includes/layout-main.liquid
# Other folder name
_test
# Other specific file
README.md
```

.. results in (DEBUG):

```
> DEBUG=Eleventy* eleventy --input=src --output=dist --formats=liquid

  Eleventy:Config Setting up global TemplateConfig. +0ms
  Eleventy:TemplateWriter src/.eleventyignore ignoring: ./src/_includes +0ms
  Eleventy:TemplateWriter src/.eleventyignore ignoring: ./src/_includes/layout-main.liquid +0ms
  Eleventy:TemplateWriter src/.eleventyignore ignoring: ./src/_test +1ms
  Eleventy:TemplateWriter src/.eleventyignore ignoring: ./src/README.md +0ms
  Eleventy Directories:
  Eleventy Input: src
  Eleventy Data: src/_data
  Eleventy Includes: src/_includes
  Eleventy Output: dist
  Eleventy Template Formats: liquid +0ms
  Eleventy:TemplateWriter Searching for: +9ms
  Eleventy:TemplateWriter [ 'src/**/*.liquid',
  Eleventy:TemplateWriter   '!./src/_includes/**',
  Eleventy:TemplateWriter   '!./src/_includes/layout-main.liquid',
  Eleventy:TemplateWriter   '!./src/_test/**',
  Eleventy:TemplateWriter   '!./src/README.md',
  Eleventy:TemplateWriter   '!./dist/**',
  Eleventy:TemplateWriter   '!./src/_includes/**',
  Eleventy:TemplateWriter   '!./src/_data/**' ] +0ms
  Eleventy:TemplateWriter Found: +22ms
  Eleventy:TemplateWriter [ 'src/_includes/layout-main.liquid',
  Eleventy:TemplateWriter   'src/_includes/nav.liquid',
  Eleventy:TemplateWriter   'src/_test/wat.liquid',
  Eleventy:TemplateWriter   'src/dashboard.liquid',
  Eleventy:TemplateWriter   'src/new.liquid' ] +0ms
  Eleventy:TemplateWriter Template for src/_includes/layout-main.liquid added to map. +23ms
  Eleventy:TemplateWriter Template for src/_includes/nav.liquid added to map. +2ms
  Eleventy:TemplateWriter Template for src/_test/wat.liquid added to map. +1ms
  Eleventy:TemplateWriter Template for src/dashboard.liquid added to map. +6ms
  Eleventy:TemplateWriter Template for src/new.liquid added to map. +2ms
  Eleventy:TemplateWriter Collection: collections.all has 5 items. +3ms
```

According to [TemplateWriter.js:221](https://github.com/11ty/eleventy/blob/master/src/TemplateWriter.js#L221) the files are correctly picked up and ignored for `this.files` but are nonetheless *included* in [`this._getAllPaths()`](https://github.com/11ty/eleventy/blob/master/src/TemplateWriter.js#L222)

The only file that gets correctly ignored is the README.md. And `_data/` (which I've not exluded in my ignorefile). Somehow `_includes/` *is* included.

So, for example, `this.files` includes `[.., '!./src/_test/**']` but `this._getAllPaths() => globby(this.files)` results in `[.., 'src/_test/wat.liquid']`.

Should globby not have excluded `src/_test/wat.liquid` based on `!./src/_test/**`?
Or am I missing something?

**Comment by zachleat** [comment]
First of thank you for the very complete issue report! Unfortunately I think I already noticed this over the weekend and filled it as #33 and #34. Those are fixed but not released on npm yet. Version pending!

There was an inconsistency in how the globby dependency handles `dir` and `./dir`. The next version of Eleventy normalizes to the latter version to work around this issue.

**Comment by zachleat** [comment]
Oh, for the record, you can manually use `./` dirs in your config until this is released.

**Comment by davidhund** [comment]
Aahh… Thanks for your quick reply @zachleat! — Looking forward to the new version.

FYI: I've tried updating the `.eleventyignore` as:

```
./_includes
./_test
README.md
```

But this does not seem to fix the issue:

```
> DEBUG=Eleventy* eleventy --input=src --output=dist --formats=liquid

  Eleventy:Config Setting up global TemplateConfig. +0ms
  Eleventy:TemplateWriter src/.eleventyignore ignoring: ./src/_includes +0ms
  Eleventy:TemplateWriter src/.eleventyignore ignoring: ./src/_test +0ms
  Eleventy:TemplateWriter src/.eleventyignore ignoring: ./src/README.md +1ms
  Eleventy Directories:
  Eleventy Input: src
  Eleventy Data: src/_data
  Eleventy Includes: src/_includes
  Eleventy Output: dist
  Eleventy Template Formats: liquid +0ms
  Eleventy:TemplateWriter Searching for: +7ms
  Eleventy:TemplateWriter [ 'src/**/*.liquid',
  Eleventy:TemplateWriter   '!./src/_includes/**',
  Eleventy:TemplateWriter   '!./src/_test/**',
  Eleventy:TemplateWriter   '!./src/README.md',
  Eleventy:TemplateWriter   '!./dist/**',
  Eleventy:TemplateWriter   '!./src/_includes/**',
  Eleventy:TemplateWriter   '!./src/_data/**' ] +0ms
  Eleventy:TemplateWriter Found: +31ms
  Eleventy:TemplateWriter [ 'src/_includes/layout-main.liquid',
  Eleventy:TemplateWriter   'src/_includes/nav.liquid',
  Eleventy:TemplateWriter   'src/_test/wat.liquid'] +0ms
```
Using `./_test` in the ignoreFile still results in `src/_test/wat.liquid` being included, same as `./_includes`…

**Comment by zachleat** [comment]
Oh, sorry. I meant the format should be used for your input directory, this part:

```
Eleventy Input: src
  Eleventy Data: src/_data
  Eleventy Includes: src/_includes
  Eleventy Output: dist
```

**Comment by davidhund** [comment]
👍🏻  Using `eleventy --input=./src --output=./dist` works. Thanks Zach!
